url : "https://cs-uob.github.io"
baseurl : "/COMS30048"
remote_theme : "just-the-docs/just-the-docs"

title : "COMS30048"
description : ""

aux_links :
  "COMS30048 via Blackboard" : "https://www.ole.bris.ac.uk"

color_scheme : light

search_enabled : true
heading_anchors : false

back_to_top : true
back_to_top_text : "Back to top"

permalink : pretty
