repository: "cs-uob/COMS30048"
url: "https://cs-uob.github.io"
baseurl: "/COMS30048"
remote_theme: "mmistakes/minimal-mistakes@4.26.2"

title: "COMS30048"
subtitle: "Applied Cryptology"
title_separator: "|"

copyright: "COMS30048"
copyright_url: "https://cs-uob.github.io/COMS30048"
minimal_mistakes_skin: "contrast"
locale: "en"
enable_copy_code_button: true
breadcrumbs: false
search: false
atom_feed:
  hide: true

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      classes: wide
      header:
        image: "/assets/image/banner.png"
      sidebar:
        nav: "side"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/bristolcs"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/cs-uob"
